### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ser** [TerenceAnton/fona-simduino#1]
Hi, the link related to soldiering is broken, do you have a copy by any chance?

**Comment by tobeedelafuente** [comment]
Hi @ser, apparently the link doesn't work anymore. Check out the readme again for the picture

**Comment by ser** [comment]
Thanks a lot! One more question if possible - have you replaced the GPS antennae which comes with simduino? If yes, to which one? Cheers :-)

**Comment by tobeedelafuente** [comment]
Most of the time I leave as is but if I need to put the board indoors (the GPS signal can't go in most of the time) I attach this: https://circuit.rocks/gps-active-antenna-3m-plug-series-connector-sma.html. If you will buy something similar just take note that these outdoors type antenna use SMA connectors. You will need an SMA to UFL connector.

In any case that the antenna is broken (it's possible that due to bending the square thingy breaks off) you may get something like this: https://circuit.rocks/antenna-passive-gps-ufl-15mm-x-15mm-1-dbi-gain.html

**Comment by ser** [comment]
I soldered today the power button, amazing! Thanks for the tip!!!!

I do not see in your examples any GPRS communication, you have not used that part of library at all?

**Comment by tobeedelafuente** [comment]
I haven't tried using GPRS communication with the Adafruit FONA. You may check the library for the GPRS example if ever
